In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn import metrics
import os, sys

In [5]:
# set random state
seed = 69

## Load Dataset

In [7]:
filepath = '../../data/interim/data_op_01.csv'
data_op_1 = pd.read_csv(filepath, )
data_op_1.head()

,unit,time_step,operational_setting_1,operational_setting_2,operational_setting_3,Sensor_0,Sensor_1,Sensor_2,Sensor_3,Sensor_4,...,Sensor_13,Sensor_14,Sensor_15,Sensor_16,Sensor_17,Sensor_18,Sensor_19,Sensor_20,Health_state,Operational_condition
0,1,1,10.0047,0.2501,20.0,489.05,604.13,1499.45,1309.95,10.52,...,8120.83,8.6216,0.03,368,2319,100.0,28.58,17.1735,1,1
14,1,15,9.9988,0.2500,20.0,489.05,604.63,1497.87,1302.51,10.52,...,8124.37,8.6496,0.03,369,2319,100.0,28.84,17.0805,1,1
15,1,16,9.9987,0.2500,20.0,489.05,604.61,1500.47,1311.39,10.52,...,8127.07,8.6609,0.03,369,2319,100.0,28.71,17.1759,1,1
17,1,18,10.0066,0.2507,20.0,489.05,604.23,1502.57,1304.56,10.52,...,8119.39,8.6646,0.03,367,2319,100.0,28.60,17.1096,1,1
35,1,36,10.0024,0.2504,20.0,489.05,604.43,1499.85,1306.89,10.52,...,8121.73,8.6260,0.03,369,2319,100.0,28.52,17.1036,2,1

Then, drop the labels

In [8]:
labels_op_01 =  np.array(data_op_1['Health_state'])

# Pipeline

In [15]:
from phm08ds.features.feature_selection import SelectSensors

tf_select_sensors = SelectSensors(kind='custom', sensors=[1,2,3,6,8,10,11,12,13,14,19,20])
data_op_1 = tf_select_sensors.fit_transform(data_op_1)
data_op_1.head()

,unit,time_step,operational_setting_1,operational_setting_2,operational_setting_3,Sensor_1,Sensor_2,Sensor_3,Sensor_6,Sensor_8,Sensor_10,Sensor_11,Sensor_12,Sensor_13,Sensor_14,Sensor_19,Sensor_20,Operational_condition,Health_state
0,1,1,10.0047,0.2501,20.0,604.13,1499.45,1309.95,394.88,8770.20,45.40,372.15,2388.13,8120.83,8.6216,28.58,17.1735,1,1
14,1,15,9.9988,0.2500,20.0,604.63,1497.87,1302.51,394.93,8771.08,45.39,371.84,2388.12,8124.37,8.6496,28.84,17.0805,1,1
15,1,16,9.9987,0.2500,20.0,604.61,1500.47,1311.39,394.44,8775.86,45.52,372.19,2388.08,8127.07,8.6609,28.71,17.1759,1,1
17,1,18,10.0066,0.2507,20.0,604.23,1502.57,1304.56,394.31,8778.55,45.10,372.03,2388.06,8119.39,8.6646,28.60,17.1096,1,1
35,1,36,10.0024,0.2504,20.0,604.43,1499.85,1306.89,394.36,8771.15,45.36,371.77,2388.11,8121.73,8.6260,28.52,17.1036,1,2

In [16]:
from phm08ds.features.feature_selection import RemoveInfo

tf_remove_info = RemoveInfo()

data_with_features = tf_remove_info.fit_transform(data_op_1)
data_with_features.head()

,Sensor_1,Sensor_2,Sensor_3,Sensor_6,Sensor_8,Sensor_10,Sensor_11,Sensor_12,Sensor_13,Sensor_14,Sensor_19,Sensor_20,Health_state
0,604.13,1499.45,1309.95,394.88,8770.20,45.40,372.15,2388.13,8120.83,8.6216,28.58,17.1735,1
14,604.63,1497.87,1302.51,394.93,8771.08,45.39,371.84,2388.12,8124.37,8.6496,28.84,17.0805,1
15,604.61,1500.47,1311.39,394.44,8775.86,45.52,372.19,2388.08,8127.07,8.6609,28.71,17.1759,1
17,604.23,1502.57,1304.56,394.31,8778.55,45.10,372.03,2388.06,8119.39,8.6646,28.60,17.1096,1
35,604.43,1499.85,1306.89,394.36,8771.15,45.36,371.77,2388.11,8121.73,8.6260,28.52,17.1036,2

In [23]:
data_with_features.to_csv('../../data/interim/data_op_01_sensor_Navar.csv')

In [18]:
from sklearn.preprocessing import StandardScaler

tf_std_scaller = preprocessing.StandardScaler()
data_with_features_std = tf_std_scaller.fit_transform(data_with_features)
data_with_features_std

array([[-1.66575294, -0.46078266, -0.16893857, ...,  0.37766506,
         0.67593128, -2.01497062],
       [-0.60824032, -0.73264726, -1.06544604, ...,  2.17941314,
        -0.40216143, -2.01497062],
       [-0.65054083, -0.28527512,  0.00457901, ...,  1.2785391 ,
         0.70375303, -2.01497062],
       ...,
       [ 1.76058794,  1.3837671 ,  1.64094613, ..., -0.93899701,
        -0.46823808,  1.306208  ],
       [ 2.18359299,  0.99833879,  1.8867627 , ..., -2.04776506,
        -1.91265047,  1.306208  ],
       [ 1.50678491,  0.44772693,  1.865073  , ..., -0.45391098,
        -0.46823808,  1.306208  ]])

In [19]:
X = data_with_features_std
y = labels_op_01

In [20]:
from sklearn.pipeline import Pipeline

data_preprocessing = Pipeline([('select_sensors', tf_select_sensors),
                               ('remove_info', tf_remove_info),
                               ('std_scaler', tf_std_scaller)
                              ])

In [22]:
from sklearn.externals import joblib

joblib.dump(data_preprocessing, '../../models/pipeline/select-sensorNavar_remove-info_std-scaller-OP1.pkl')

['../../models/pipeline/select-sensorNavar_remove-info_std-scaller-OP1.pkl']